source 'https://rubygems.org'
# Rails
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Model serialization
gem 'active_model_serializers'

# Font Awesome icons
gem 'font-awesome-rails'

# Paging
gem 'kaminari'

gem 'rspec-rails'

gem 'jasmine-rails'

gem 'capybara'
